version: '3.7'
services:
    nginx:
        image: nginx:alpine
        container_name: ivy_nginx
        volumes:
            - ./proxy.conf:/etc/nginx/proxy.conf
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:8080
